data_directory = './data/'
version = 203
port = 43594
max_players = 2048
packet_handler_table = 'packets.toml'

[database]
player_db = "players.db"
world_db = "world.db"

[crypto]
rsa_key = 'rsa.der'
hash_salt = 'rscgo./GOLANG!RULES/.1994'