# The directory that holds any subsequent files mentioned.
data_directory = './data/'
# The version number of the latest client release.
version = 204
# TCP/IP port number to listen for incoming connections on.
port = 43594
# Maximum number of players that this server can support.
max_players = 2048
# The TOML file containing incoming packet definitions.
packet_handler_table = 'packets.toml'

[database]
# The SQL database driver to use when connecting to the player saves database.
# SQLite3
player_driver = "sqlite3"
# PostgreSQL
# player_driver = "postgres"
# The SQL connection string for the player saves database.
# SQLite3
player_db = "file:/./data/players.db"
# Postgresql
# player_db = "host=127.0.0.1 port=5432 user=zach password=zebra1 dbname=rscgo sslmode=disable"
# The SQLite3 database containing game world/entity data.
world_db = "world.db"

[crypto]
# Length of hash output
hash_length = 32
# How many passes to do over the memory
hash_complexity = 15
# How much memory to use, in MiB
hash_memory = 8
# Salt to make hash output unique
hash_salt = 'rscgo./GOLANG!RULES/.1994'

# The RSA key file, for decrypting the login/newplayer blocks.
rsa_key = 'rsa.der'
